### PR TITLE
Update example usage

### PR DESCRIPTION
**Pull request by cardil**
Updating example usage to follow docker guidlines:

```
owner-or-company/imagename:version
```

### CODE REVIEW

**Comment by piecioshka** [comment]
@cardil Thanks!

Where I can read docker guidelines?

**Comment by cardil** [comment]
Here: https://docs.docker.com/

Unfortunately docs have degraded with latest releases, so I can't point you to exact sentence. :sob:

**Comment by cardil** [comment]
Here, more or less: https://docs.docker.com/engine/reference/commandline/tag/

> An image name is made up of slash-separated name components, optionally prefixed by a registry hostname. The hostname must comply with standard DNS rules, but may not contain underscores. If a hostname is present, it may optionally be followed by a port number in the format :8080. If not present, the command uses Docker’s public registry located at registry-1.docker.io by default. Name components may contain lowercase letters, digits and separators. A separator is defined as a period, one or two underscores, or one or more dashes. A name component may not start or end with a separator.
>
> A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.

**Comment by piecioshka** [comment]
Thanks @cardil !

I just saw rating (on the bottom of page) 💃 

```text
Rate this page:
 186 UP / 156 DOWN
```

Did you know why people doesn't like that page? 😢

**Pull request merged**
